// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/home/Banner.vue')['default']
    BaseCourse: typeof import('./src/components/common/BaseCourse.vue')['default']
    Bubble: typeof import('./src/components/common/Bubble.vue')['default']
    Controller: typeof import('./src/components/common/Controller.vue')['default']
    CourseItem: typeof import('./src/components/video/CourseItem.vue')['default']
    DialogCpn: typeof import('./src/components/common/DialogCpn.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ExcellentCourse: typeof import('./src/components/common/ExcellentCourse.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    InvestmentJournal: typeof import('./src/components/home/InvestmentJournal.vue')['default']
    JournalItem: typeof import('./src/components/common/JournalItem.vue')['default']
    LiveButton: typeof import('./src/components/common/LiveButton.vue')['default']
    LiveLog: typeof import('./src/components/common/LiveLog.vue')['default']
    LiveService: typeof import('./src/components/home/LiveService.vue')['default']
    LiveVideoItem: typeof import('./src/components/common/LiveVideoItem.vue')['default']
    ModuleHeader: typeof import('./src/components/common/ModuleHeader.vue')['default']
    MoreLive: typeof import('./src/components/home/MoreLive.vue')['default']
    Obscuration: typeof import('./src/components/common/Obscuration.vue')['default']
    Over: typeof import('./src/components/common/Over.vue')['default']
    PageStatus: typeof import('./src/components/common/PageStatus.vue')['default']
    PlayState: typeof import('./src/components/video/PlayState.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VideoItem: typeof import('./src/components/common/VideoItem.vue')['default']
    VideoList: typeof import('./src/components/home/VideoList.vue')['default']
    VideoListBody: typeof import('./src/components/common/VideoListBody.vue')['default']
    VideoPlayer: typeof import('./src/components/video/VideoPlayer.vue')['default']
    Views: typeof import('./src/components/home/Views.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
